name: Build image and publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.sh'

jobs:
  release:
    name: Create github release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "RELEASE_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - name: Create Github release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ env.RELEASE_DATE }}"
          title: "${{ env.RELEASE_DATE }}"
          files: |
            LICENSE
            cloudflare-ddns.sh

  docker:
    name: Deploy to Docker Hub (latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "RELEASE_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          no-cache: true
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: |
            afonsoc12/cloudflare-ddns:latest
            afonsoc12/cloudflare-ddns:${{ env.RELEASE_DATE }}
            ghcr.io/afonsoc12/cloudflare-ddns:latest
            ghcr.io/afonsoc12/cloudflare-ddns:${{ env.RELEASE_DATE }}
